name: Build and Release Binaries

on:
  workflow_dispatch:
    inputs:
      githubRef:
        description: "The tag to associate with the release"
        required: true

jobs:
  # step 1
  build-binary:
    name: Build executable (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        ref: ${{ inputs.githubRef }}
        submodules: 'recursive'
        fetch-depth: 0 # needed by hatch-vcs version detection

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"

    - name: Install dependencies
      shell: bash
      run: bash scripts/install-build-deps.sh

    - name: Build binary with PyInstaller
      shell: bash
      run: bash scripts/build-binary.sh

    - name: Upload executable
      uses: actions/upload-artifact@v7
      with:
        name: lancet-${{ runner.os }}
        path: dist/lancet*

  # step 2
  github-release:
    name: Create GitHub release
    needs:
    - build-binary
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download all binary artifacts
      uses: actions/download-artifact@v8
      with:
        path: binaries/
        pattern: lancet-*
        merge-multiple: true

    - name: Create GitHub release
      uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ inputs.githubRef }}
        name: "Lancet ${{ inputs.githubRef }}"
        generate_release_notes: true
        prerelease: false
        files: |
          binaries/*
